import io
import json
import re
import zipfile

from fastapi import APIRouter, Depends
from fastapi.responses import Response
from sqlmodel import Session, select

from ..config import abs_data_path
from ..db import get_session
from ..models import Character, ImageAsset, Location, Project, Scene
from ..services.crud import get_or_404, group_images, group_lines, scene_groups

router = APIRouter(prefix="/api", tags=["export"])

EXPORTABLE = {"approved", "imaging", "images_ready", "done"}


def playthrough_data(session: Session, project_id: int, include_drafts: bool = False) -> dict:
    project = get_or_404(session, Project, project_id)
    chars = list(session.exec(select(Character).where(Character.project_id == project_id)))
    locs = {l.id: l for l in session.exec(select(Location).where(Location.project_id == project_id))}
    scenes = []
    for scene in session.exec(select(Scene).where(Scene.project_id == project_id).order_by(Scene.order, Scene.id)):
        loc = locs.get(scene.location_id) if scene.location_id else None
        groups = []
        for g in scene_groups(session, scene.id):
            if g.status not in EXPORTABLE and not include_drafts:
                continue
            image = session.get(ImageAsset, g.selected_image_id) if g.selected_image_id else None
            if image is None:
                imgs = group_images(session, g.id)
                image = imgs[0] if imgs else None
            groups.append(
                {
                    "id": g.id,
                    "order": g.order,
                    "image": image.path if image else None,
                    "lines": [
                        {
                            "speaker_id": l.speaker_id,
                            "speaker": l.speaker_name,
                            "text": l.text,
                            "emotion": l.emotion,
                            "action": l.action,
                        }
                        for l in group_lines(session, g.id)
                    ],
                }
            )
        scenes.append(
            {
                "id": scene.id,
                "title": scene.title,
                "summary": scene.summary,
                "status": scene.status,
                "background": loc.image_path if loc and loc.image_path else None,
                "groups": groups,
            }
        )
    return {
        "project": {"id": project.id, "name": project.name, "premise": project.premise},
        "characters": [{"id": c.id, "name": c.name, "color": c.color} for c in chars],
        "scenes": scenes,
    }


@router.get("/projects/{project_id}/playthrough")
def playthrough(project_id: int, drafts: bool = False, session: Session = Depends(get_session)) -> dict:
    return playthrough_data(session, project_id, drafts)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_") or "project"


def _renpy_str(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("[", "[[")
        .replace("{", "{{")
        .replace("\n", " ")
    )


def _renpy_var(name: str, used: set[str]) -> str:
    base = re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_") or "char"
    var = f"c_{base}"
    n = 2
    while var in used:
        var = f"c_{base}{n}"
        n += 1
    used.add(var)
    return var


@router.get("/projects/{project_id}/export/renpy")
def export_renpy(project_id: int, session: Session = Depends(get_session)) -> Response:
    data = playthrough_data(session, project_id)
    used: set[str] = set()
    var_by_id = {c["id"]: _renpy_var(c["name"], used) for c in data["characters"]}
    out = [
        f"# Generated by VN Flow - {data['project']['name']}",
        "# Copy the contents of game/ into your Ren'Py project's game/ folder, then make your",
        "# script.rpy start the story with:   label start:\n#     jump vnflow_start",
        "",
        'transform vnflow_fit:\n    xysize (config.screen_width, config.screen_height)\n    fit "cover"',
        "",
    ]
    for c in data["characters"]:
        out.append(f'define {var_by_id[c["id"]]} = Character("{_renpy_str(c["name"])}", color="{c["color"]}")')
    out += ["", "label vnflow_start:"]
    playable = [s for s in data["scenes"] if s["groups"]]
    out.append(f"    jump vnflow_scene_1" if playable else "    return")

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for si, scene in enumerate(playable, start=1):
            out += ["", f"label vnflow_scene_{si}:", f"    # {_renpy_str(scene['title'])}"]
            if scene["background"]:
                bg = f"bg_s{si}"
                zf.write(abs_data_path(scene["background"]), f"game/images/{bg}.png")
                out += [f"    scene {bg} at vnflow_fit", "    with fade"]
            for gi, g in enumerate(scene["groups"], start=1):
                if g["image"] and abs_data_path(g["image"]).exists():
                    img = f"cg_s{si}_g{gi}"
                    zf.write(abs_data_path(g["image"]), f"game/images/{img}.png")
                    out += [f"    scene {img} at vnflow_fit", "    with dissolve"]
                for line in g["lines"]:
                    text = _renpy_str(line["text"])
                    var = var_by_id.get(line["speaker_id"]) if line["speaker_id"] else None
                    out.append(f'    {var} "{text}"' if var else f'    "{text}"')
            out.append(f"    jump vnflow_scene_{si + 1}" if si < len(playable) else "    return")
        zf.writestr("game/vnflow_script.rpy", "\n".join(out) + "\n")
        zf.writestr("game/vnflow_story.json", json.dumps(data, indent=2))
    name = _slug(data["project"]["name"])
    return Response(
        buf.getvalue(),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}_renpy.zip"'},
    )


@router.get("/projects/{project_id}/export/json")
def export_json(project_id: int, session: Session = Depends(get_session)) -> Response:
    project = get_or_404(session, Project, project_id)
    dump = {
        "project": project.model_dump(mode="json"),
        "characters": [c.model_dump(mode="json") for c in session.exec(select(Character).where(Character.project_id == project_id))],
        "locations": [l.model_dump(mode="json") for l in session.exec(select(Location).where(Location.project_id == project_id))],
        "story": playthrough_data(session, project_id, include_drafts=True),
    }
    return Response(
        json.dumps(dump, indent=2),
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{_slug(project.name)}.json"'},
    )
